### ISSUE TITLE
Elliptic error on build

### ISSUE THREAD

**Issue by eshcharc** [mobilexag/plugin-sass#16]
I get this error when running jspm.bundleSFX:
```javascript
Error loading "npm:elliptic@6.0.2/package.json!github:systemjs/plugin-json@0.1.0" from "github:mobilexag/plugin-sass@0.0.10/sass-builder"
```
which fails the build.

Does anyone know what the cause of this error is, and how to solve it?

I want to mention that on Dev mode, everything works perfect.

**Comment by eshcharc** [comment]
If I downgrade elliptic to 6.0.0, the previous error is resolved, but I get this new importing error:
```javascript
TypeError: Cannot read property 'call' of undefined
    at eval (file:../jspm_packages/github/mobilexag/plugin-sass@0.0.10/index.js!eval:25:38)
```

**Comment by screendriver** [comment]
Could you try to run 

```sh
$ gulp test:bundleStatic
```

as [mentioned](https://github.com/mobilexag/plugin-sass#testing-the-plugin) in the README? I tried a `$ gulp test:bundleStatic` and a `$ jspm bundle-sfx test/bundleme.js foo.js` as well and everything works fine.

**Comment by eshcharc** [comment]
Probably a matter of versions. Solved after upgrading several libs (can't tell which, though).
