### ISSUE TITLE
Unit testing 'Unhandled promise rejection' error

### ISSUE THREAD

**Issue by eshcharc** [mobilexag/plugin-sass#23]
Plugin works on Dev and Build but encounters an error when running under Karma and PhantomJS.

```
PhantomJS 1.9.8 (Windows 7 0.0.0) ERROR: 'Unhandled promise rejection', '[object XMLHttpRequest]
        Error loading http://localhost:9876/base/app/components/addin/addin.scss!http://localhost:9876/base/jspm_packages/github/mobilexag/plugin-sass
@0.1.0.js as "./addin.scss!" from http://localhost:9876/base/app/components/addin/addin.component.js'
PhantomJS 1.9.8 (Windows 7 0.0.0) ERROR
abort("Assertion failed: JS engine does not provide full typed array support") at Error: 0
    at jsStackTrace (C:/dev/jspm_packages/npm/sass.js@0.9.4/dist/sass.worker.js:15)
    at stackTrace (C:/dev/jspm_packages/npm/sass.js@0.9.4/dist/sass.worker.js:15)
    at abort (C:/dev/jspm_packages/npm/sass.js@0.9.4/dist/sass.worker.js:37)
    at assert (C:/dev/jspm_packages/npm/sass.js@0.9.4/dist/sass.worker.js:15)
    at C:/dev/jspm_packages/npm/sass.js@0.9.4/dist/sass.worker.js:15
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
at undefined
```

Is there a way to overcome this?
I can even bare a method of ignoring loading of these files (.scss) while testing (but that may be a question for Karma forum).

**Comment by screendriver** [comment]
Hi @eshcharc,

thank you for the report. But as you can see in the callstack your issue occurs in the [sass.js](https://github.com/medialize/sass.js/) library. So please open an issue there. Thank you.

**Comment by eshcharc** [comment]
Is it even possible to run the plugin with karma or that I'm fighting wind-mails here?

**Comment by screendriver** [comment]
Sorry I don't know Karma and PhantomJS.

**Comment by benjaminkitt** [comment]
@eshcharc You'll need to either use https://github.com/conversocial/phantomjs-polyfill, https://github.com/gskachkov/karma-phantomjs2-launcher or see karma-runner/karma-phantomjs-launcher#56

**Comment by eshcharc** [comment]
Thanks. It was indeed solved with PhantomJS 2.
