### ISSUE TITLE
Issues around multiple sass files being compiled, urlBase is reset each time.

### ISSUE THREAD

**Issue by dougludlow** [mobilexag/plugin-sass#26]
So I've run into an issue where when I'm importing multiple sass files, the urlBase is being reset each time which results in the urlBase being set to the last file that was compiled and breaks imports in other files.

I've attempted to fix the issue by placing urlBase in a closure instead of hanging it globally in the sass-builder/sass-inject, however, it appears that sass.js is a singleton and so anytime sass.import is called it overwrites the previous importer and the urlBase is hence overwritten.

Any ideas on how to get a different instance of sass.js for each compile?

**Comment by dougludlow** [comment]
I opened an [issue on the sass.js](https://github.com/medialize/sass.js/issues/43) repo. @rodneyrehm found a great solution to pass importer options with the rest of the options into the compile method. This will resolve the issue where the sass.sync.js synchronous apis is being used in both the builder and the loader/injector where web workers aren't used. 

I noticed an issue with the way we're resolving sass and newing it up in the loader/injector. It appears to be caching the result of the promise rather than returning a new sass.js instance each time.

I'll work on a pr to take into the account the changes @rodneyrehm is making and see if I can address the issue with the promise.

**Comment by screendriver** [comment]
Closed with pull request #27

**Comment by dougludlow** [comment]
Thanks @screendriver! When are you thinking you'll make another release?

**Comment by screendriver** [comment]
`v0.2.1` released

**Comment by dougludlow** [comment]
Sweet! Thanks again!
