### ISSUE TITLE
"ReferenceError: document is not defined" when bundling with arithmetic

### ISSUE THREAD

**Issue by ericsvendsen** [mobilexag/plugin-sass#28]
When using arithmetic to bundle external dependencies separately from my app code (as suggested in [this jspm-cli issue](https://github.com/jspm/jspm-cli/issues/1277#issuecomment-169367170)), plugin-sass throws the error:

`ReferenceError: document is not defined`

If I remove my scss import statements, then bundling succeeds.

**Comment by screendriver** [comment]
Fixed with #29
