### ISSUE TITLE
Return compiled CSS as string

### ISSUE THREAD

**Issue by KarlPurk** [mobilexag/plugin-sass#31]
Would you be open to extending the plugin to provide the ability to return the compiled css as a string?

```js
import style from './style.scss!';

@Component({
    template: '...',
    style: [style]
})
```

Cheers!

**Comment by KarlPurk** [comment]
I've implemented this in a fork, no tests or bundle support:
https://github.com/KarlPurk/plugin-sass/commit/fabd142242caa584fc50e3a4d35083d80ebdee5d

**Comment by KarlPurk** [comment]
After playing with this idea last week, I realised that this wouldn't be a very good idea.  A better idea is to create a separate plugin for this purpose.

**Comment by screendriver** [comment]
Thank you for the feedback :+1:

**Comment by frederikschubert** [comment]
I would really like having this implemented in this plugin. Would it be possible for the plugin to detect the import type? So default import vs. module import? If so the functionality should be relatively easy to implement.
Having two separate plugins for importing sass files into my project is no optimal solution and I would like to make use of both ways.

**Comment by screendriver** [comment]
I don't know if this is possible with SystemJS plugins. You can look at the plugin [API](https://github.com/systemjs/systemjs/blob/master/docs/creating-plugins.md).

I believe you have to implement `fetch` **and** `translate` but I don't know how to set a result in `fetch` and give it to `translate`. The SystemJS internals are not known to me.

Any pull requests are welcome.

**Comment by KarlPurk** [comment]
This is possible, but the problem with implementing this with a single plugin is what drives the decision to import vs inject?

I originally thought this could be driven at design time by config, but then you are limited to one or the other option.

The best solution would probably be to chain multiple loaders (similar to webpack) but I don't think systemjs currently supports this? - and this would still require two loaders, one for scss and one for injecting into head.

For our use case, my colleague developed [plugin-scss](https://github.com/KevCJones/plugin-scss) which allows scss to be imported as a string.  We can then inject it into the head manually if we desire or work with the compiled scss directly.

**Comment by screendriver** [comment]
Ah I understand :+1:
This is indeed a different approach as this plugin was designed for. Also I don't know if it's a good idea to mix the behaviour of this plugin with the different approach of your plugin so I think it's the best solution to have two different plugins for that. Maybe in the future it is possible to have chained multiple loaders in SystemJS / jspm so we can merge together :sunglasses:

**Comment by KevCJones** [comment]
Watching that space :sunglasses: 

If nothing else the variation we have is useful for our needs with angular2 and it was highly educating to write when learning JSPM and SystemJS. So thanks for the starting point. :+1:
