### ISSUE TITLE
Partial Imports are not requested properly under certain configurations.

### ISSUE THREAD

**Issue by gscoppino** [mobilexag/plugin-sass#32]
SASS partial imports requests are not working properly for me. If I load a SASS file like so:

`System.import('main.scss!')`

and that file `main.scss` imports a file like so:

`@import 'some/partial';`

Then the request is made to:

`http://some/partial.scss`

I would have expected the request to be made on the domain, ie.

`http://localhost:8080/some/partial.scss`

Thank you for the great work on this plugin @screendriver :)

**Comment by gscoppino** [comment]
In `sass-inject.js`:

`
export default load => {
  const urlBase = path.dirname(url.parse(load.address).pathname) + '/';
  ...
};
`

It appears the trailing slash is not necessary? Seems to be the source of the requests not being created correctly by `reqwest`. Upon removal, partial imports are working correctly.

**Comment by screendriver** [comment]
Hi @gscoppino,

if you look at the [unit tests](https://github.com/mobilexag/plugin-sass/tree/master/test) you can see that partial imports **should** work. Maybe I oversight anything? Are the tests running on your machine?

**Comment by gscoppino** [comment]
I don't see my use case tested in here, what I'm trying to do is import a local resource directly.

**Comment by gscoppino** [comment]
I created a test [here](https://github.com/gscoppino/plugin-sass/commit/821a8c5dfb87ea417fb1283d425649010556cfb9) for what is happening.

**Comment by gscoppino** [comment]
I dug into this issue I was having a little more today, especially since I couldn't reproduce it in the existing tests.  It seems that the problem is that in most cases (including the tests) there is some sort of base directory that SystemJS is importing from. It could be that an import was done of the form `System.import('styles/base.scss!')` with a SystemJS `baseURL` of `/`, or it could be that an import of the form `System.import('base.scss!`)` with a SystemJS `baseURL` of `/static`. Or a combination of the two. In these cases, appending a trailing slash to the parsed load address makes sense. 

However, in my project, I have a SystemJS `baseURL` of `/` and an import of `System.import('main.scss!')`. So once `plugin-sass` parses the load address, it ends up with `/`. Appending another `/` to that breaks the request resolver.

**Comment by screendriver** [comment]
Fixed with #45
