### ISSUE TITLE
Build error in sass.worker.js (0.9.7)

### ISSUE THREAD

**Issue by elsifaka** [mobilexag/plugin-sass#33]
`jspm update` in my projet updated `sass.js` to `0.9.7` then I ran into the issue described here
https://github.com/medialize/sass.js/issues/47#issuecomment-185228411 (files needed for testing are there). I don't know where to start to resolve the issue. `sass.js@0.9.6` does work well.

**Comment by screendriver** [comment]
`plugin-sass` uses `0.9.6` so there is no need to update manually `sass.js` to `0.9.7`. Just install the plugin and all other dependencies will be installed automatically.
