### ISSUE TITLE
nested imports not found

### ISSUE THREAD

**Issue by faboweb** [mobilexag/plugin-sass#38]
Hi,
nested imports are not found.

Example:
```
Uncaught (in promise) Error: Error: File to import not found or unreadable: settings/prefixer
       Parent style sheet: http://localhost:3000/x/jspm_packages/npm/bourbon@4.2.6/app/assets/stylesheets/bourbon.scss
        on line 6 of http://localhost:3000/x/jspm_packages/npm/bourbon@4.2.6/app/assets/stylesheets/bourbon.scss
>> @import "settings/prefixer";
```

Using version 0.2.1 in version 0.16.30 of jspm.

**Comment by screendriver** [comment]
Nested imports should work. Could you please checkout this project and run my unit tests as mentioned in the [README](https://github.com/mobilexag/plugin-sass#testing-the-plugin)? When the tests are running on your machine then there is something wrong in your project **or** I missed a test :wink:

**Comment by faboweb** [comment]
This seems to be related to #39.
