### ISSUE TITLE
dependency 'url' does not resolve

### ISSUE THREAD

**Issue by faboweb** [mobilexag/plugin-sass#39]
Hi,
in sass-inject.js the dependency 'url' does not resolve. Throwing an error at the line
```
var urlBase = path.dirname(url.parse(load.address).pathname) + '/';
```
Using version 0.2.1 in version 0.16.30 of jspm.

**Comment by screendriver** [comment]
Hi,

[url](https://www.npmjs.com/package/url) is imported in line [7](https://github.com/mobilexag/plugin-sass/blob/master/src/sass-inject.js#L7) and declared as a [direct dependency](https://github.com/mobilexag/plugin-sass/blob/master/package.json#L55) so I guess there went something wrong as you installed the package.

Could you try to remove your `jspm_packages` directory and make a new `jspm install` on your project and look at the output?

**Comment by faboweb** [comment]
I did a fresh init of jspm. Removed jspm_packages before. Still url is not resolved. All the other dependencies in sass-inject.js are resolved.

**Comment by screendriver** [comment]
Could you post the content of your `jspm_packages` directory?

Do you have tried to run the unit tests of this project here? Is there still this error? Do you have a sample project on GitHub which I can clone?

**Comment by faboweb** [comment]
Attached is the folder structure.
[output.txt](https://github.com/mobilexag/plugin-sass/files/161624/output.txt)

**Comment by screendriver** [comment]
> I tried the tests. They are working. So not a problem with the pure plugin.

Hm I don't have any idea what's going wrong on your machine. It could help me a lot when you make a sample project here on GitHub where I can reproduce your issue.

**Comment by screendriver** [comment]
Temporarily closed because not reproducable. Please let me know if you have still this problem.

**Comment by doingweb** [comment]
Not sure if I actually had the same error, but I found that the imports for both `url` and `path` were looking for files in my app directory rather than for the respective `nodelibs` packages. I added mappings for `path` and  `url` in my SystemJS config (and installed `nodelibs-url` manually) to get it working:

```js
[...]
    "github:dougludlow/plugin-sass@0.6.0": {
      "autoprefixer": "npm:autoprefixer@6.7.7",
      "css-asset-copier": "npm:css-asset-copier@1.0.2",
      "css-url-rewriter-ex": "npm:css-url-rewriter-ex@1.0.6",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "postcss": "npm:postcss@5.2.17",
      "reqwest": "github:ded/reqwest@2.0.5",
      "sass.js": "npm:sass.js@0.9.13",
      "url": "jspm/nodelibs-url"
    },
[...]
```
