### ISSUE TITLE
Any way to just grab the output css from the import?

### ISSUE THREAD

**Issue by te-je** [mobilexag/plugin-sass#41]
Similar to how [plugin-text](https://github.com/systemjs/plugin-text) does it. This is useful for angular2, where injecting directly into the head has no effect. Instead, you do something like:

```typescript
import styleText from './path/to/file.scss!';

@Component({
  ...
  styles: [styleText]
})
export class Component { }
```

**Comment by screendriver** [comment]
Dup of #31
