### ISSUE TITLE
Installed fine, but can't seem `load` the scss file. "Error loading file".

### ISSUE THREAD

**Issue by piggyslasher** [mobilexag/plugin-sass#48]
I've installed the plug-in as recommended.

In my `home.component.js` file, line 3 was this previously.

```javascript
import './home.css!';
```
As in:

![d2](https://cloud.githubusercontent.com/assets/1991125/14274441/f062a086-fb43-11e5-8a61-1d1c49f9f47a.png)

I've renamed the file to `home.scss`

I've changed the import line to:
```javascript
import './home.scss!';
```

But I still get an error like so in the console:
```
Error: 
	Error loading http://localhost:3000/scss.js
	Error loading http://localhost:3000/home.scss!http://localhost:3000/scss.js
```

Folder structure:
![d3](https://cloud.githubusercontent.com/assets/1991125/14274503/58a97f48-fb44-11e5-9c05-d3e08a726a37.png)

Any help appreciated. Just getting a hang of `jspm`.

**Comment by screendriver** [comment]
Could you please create a sample GitHub project where I can reproduce your issue?

**Comment by piggyslasher** [comment]
You sir, are a *star*.

https://github.com/piggyslasher/NG6-starter/tree/jspm

It's here. It's a fork of [this](https://github.com/AngularClass/NG6-starter). But a small fork. Just added your scss plugin.

**Comment by screendriver** [comment]
I can't see the SASS plugin in the [dependencies](https://github.com/piggyslasher/NG6-starter/blob/jspm/package.json#L22) so it cannot work.

**Comment by piggyslasher** [comment]
Really sorry. There seemed to be some error when installing your plugin. Not sure what's going on here. My bad. I was running way too many commands in one line. I'm now debugging this error. Have you come across this?

```bash
$ jspm install scss=sass
     Updating registry cache...
     Looking up github:mobilexag/plugin-sass
     Looking up npm:autoprefixer
     Looking up npm:lodash
     Looking up npm:postcss
     Looking up npm:sass.js
     Looking up npm:supports-color
     Looking up npm:source-map
     Looking up npm:js-base64
     Looking up npm:postcss-value-parser
     Looking up npm:normalize-range
     Looking up npm:num2fraction
     Looking up npm:browserslist
     Looking up npm:caniuse-db
ok   Installed npm:postcss@^5.0.18 (5.0.19)
ok   Installed npm:autoprefixer@^6.3.3 (6.3.6)
ok   Installed npm:sass.js@^0.9.6 (0.9.7)
ok   Installed npm:lodash@^4.6.1 (4.8.2)
ok   Installed npm:source-map@^0.5.1 (0.5.3)
     Looking up npm:has-flag
ok   Installed npm:supports-color@^3.1.2 (3.1.2)

warn Error on lookup for npm:js-base64
     Unable to parse package.json

err  Error looking up npm:js-base64.

warn Installation changes not saved.
```

**Comment by piggyslasher** [comment]
Closing for now. Seems to be out of your scope. Apologies. First day with JSPM.
