### ISSUE TITLE
Angular2 use case

### ISSUE THREAD

**Issue by triarc** [mobilexag/plugin-sass#52]
In Angular2 you can specify the styles on component base. This is usefull for shadow dom behaviour where the css only applies to that certain component. So as soon as the component gets unloaded, the css also disappears from the dom.
To achieve that, you can pass either the css url to the component or the css itself. Now it would be usefull if the sass plugin would be able to return the compiled sass so we can pass it into the angular2 component directly. The benefit over passing the url to the component is the bundling functionality which would allow to bundle the components logic (js), the html template (therefore I'd use the text plugin) and the css (with this plugin).
My proposal would be to add an option (maybe even on a resource base if possible) where we skip the dom injection of the sass and return the css as string.

**Comment by screendriver** [comment]
This plugin was meant for a different use case than yours. Please look at issue #31 for a solution and the forked repo [plugin-scss](https://github.com/KevCJones/plugin-scss) that does exactly what you want.
