### ISSUE TITLE
When installing module B within module A it results in a GET with a non-flat path to B's dependencies.

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [mobilexag/plugin-sass#54]
Hi thanks for the great plugin,  

I have an issue but I'm not sure where it belongs. Created a it jspm. Please see the issue  jspm/jspm-cli#1752.

Thanks.

**Comment by marthinus-engelbrecht** [comment]
This ended up being my issue. I thought that I couldn't use the `jspm:` syntax with npm dependencies but it turns out you can. So the import should be: 
```scss
@import "jspm:material-design-lite/src/material-design-lite.scss";
```

**Comment by screendriver** [comment]
Thank you for the feedback 👍 In the last days I hadn't the time to investigate your issue. Great to hear that it's solved.

**Comment by marthinus-engelbrecht** [comment]
Yeah, I think it might make sense though to have syntax specifically for npm, some like `npm:`. I think it would be a bit more idiomatic with how the rest of `jspm` works.
