### ISSUE TITLE
Not working in Safari 8

### ISSUE THREAD

**Issue by erwinverdonk** [mobilexag/plugin-sass#56]
Your plugin is not working in Safari 8, it appears to stop executing other parts of SystemJS as well. Just to know it wasnt my applications fault, I ran your 'test:runtime' on Safari 8 and noticed the same behaviour there. 

Please let me know when there is anything I can help you with solving this.

Kind Regards,
Erwin Verdonk

**Comment by screendriver** [comment]
I can only test in Safari 9.1 and there is everything working as expected. So unfortunately I can't directly help debugging what's going on 😕

**Comment by sormy** [comment]
This PR should fix issue: https://github.com/mobilexag/plugin-sass/pull/73
