### ISSUE TITLE
About "Note: please use the latest stable release"

### ISSUE THREAD

**Issue by ineentho** [mobilexag/plugin-sass#58]
I don't think that note is necessary, we are using 0.4.3 with jspm beta 14 without any problems whatsoever. We use most features including imports and autoprefixer, so I'd say this plugin is 0.17 ready. It even works with meta overrides as is recommended in 0.17:

```
"meta": {
        "*.scss": {
          "loader": "sass"
        }
}
```

**Comment by screendriver** [comment]
Thank you for that information 👍 I know that there **were** problems with early betas of jspm `0.17`. After that I didn't tested it anymore. Great to here that it's working with the current beta. I will remove that note from the README.
