### ISSUE TITLE
Building a separate css file

### ISSUE THREAD

**Issue by johnste** [mobilexag/plugin-sass#61]
Are there any plans in supporting `separateCSS` or `buildCSS` options that are available in [plugin-css](https://github.com/systemjs/plugin-css)? Or is there an alternative to those options? # #

**Comment by screendriver** [comment]
At the moment not. But thank you for the hint, I will add it to my to do list.

Alternative you could make a pull request for that if you want :blush:

**Comment by sormy** [comment]
This PR should fix issue: https://github.com/mobilexag/plugin-sass/pull/73
