### ISSUE TITLE
trying to import a jspm module from a sass file

### ISSUE THREAD

**Issue by worldspawn** [mobilexag/plugin-sass#64]
hi i'm trying to import angular-material's sass.

in my js i have `import './portal.scss!';` and in portal.scss i have `@import "jspm:angular-material/angular-material";`

i'm getting the error: `reqwest.js:240 GET http://127.0.0.1:8001/jspm_packages/npm/angular-material@1.1.0-rc.5/_angular-material.scss 404 (Not Found)`

there is no _angular-material.scss only angular-material.scss. is there some convention i need to use in the import to stop it adding the underscore?

**Comment by worldspawn** [comment]
never mind, i see it requests that, fails then tries without the underscore.

**Comment by martinmicunda** [comment]
@worldspawn how did you fix this problem as I can see exactly same 404 error as you did...

**Comment by worldspawn** [comment]
I didn't really. It just makes two requests. Seems to be the intended behaviour, honestly I gave jspm the flick as it took ages to refresh after a change

**Comment by screendriver** [comment]
> honestly I gave jspm the flick as it took ages to refresh after a change

Yes that's true. Because of this and other issues we moved internally to [webpack](https://webpack.github.io/).
