### ISSUE TITLE
Code crashes on missing endsWith

### ISSUE THREAD

**Issue by nelisbijl** [mobilexag/plugin-sass#67]
Potentially unhandled rejection [3] (SystemJS) TypeError: Object doesn't support property or method 'endsWith'

This is in sass-inject:
  const indentedSyntax = load.address.endsWith('.sass');

**Comment by nelisbijl** [comment]
Solved this by adding the following to SystemJS.config meta section:

"scss": {
      "deps": [
         "babel/browser-polyfill.js"
      ]  
    },

Q1: is this a proprer solution?
Q2: why does this package not include the proper dependency?

**Comment by screendriver** [comment]
Which Browser (and version) do you use? `.endsWith()` should be supported by [all](http://kangax.github.io/compat-table/es6/#test-String.prototype.endsWith) modern browsers.

By the way: as a general rule of thumb you should **always** import the Babel polyfill as described [here](https://babeljs.io/docs/usage/polyfill/) at the very first beginning of your scripts. With the polyfill you ensure that all plugins, code, runtimes are working as expected.

**Comment by nelisbijl** [comment]
Ok, using the polyfill
