### ISSUE TITLE
Bundles containing plugin-sass fails to load at runtime due to the use of __moduleName

### ISSUE THREAD

**Issue by kawazoe** [mobilexag/plugin-sass#69]
I am trying to improve the refresh speed of my application during development by bundling the various plugins that I am using. The only plugin causing an issue so far (and the most expensive to load) is this one; the sass plugin.

I get a `ReferenceError: __moduleName is not defined` when loading the index module. I am using the babel transpiler with systemjs v0.19.31 and plugin-sass v0.4.6.

**Comment by kawazoe** [comment]
@screendriver Any idea how this could be fixed? I am starting to consider moving away from sass until this can be fixed...

**Comment by screendriver** [comment]
Sorry for the delayed response. I oversight your issue.
Do you have a sample project where I can reproduce it? As you can see in my [test](https://github.com/mobilexag/plugin-sass/blob/master/package.json#L26) bundling should work out of the box.

**Comment by kawazoe** [comment]
Here is a repository that reproduce this issue: [kawazoe/plugin-sass-bundle](https://github.com/kawazoe/plugin-sass-bundle). All the instructions are in the readme.

**Comment by screendriver** [comment]
I did a

```sh
$ npm install
...
$ npm run bundle

> application-name@0.0.1 bundle /home/me/plugin-sass-bundle
> jspm bundle scss --inject

     Building the bundle tree for scss...
     
       github:jspm/nodelibs-process@0.1.2.js
       github:jspm/nodelibs-process@0.1.2/index.js
       github:mobilexag/plugin-sass@0.4.6.js
       github:mobilexag/plugin-sass@0.4.6/index.js
       npm:babel-runtime@5.8.38/core-js/object/create.js
       npm:babel-runtime@5.8.38/core-js/object/set-prototype-of.js
       npm:babel-runtime@5.8.38/core-js/promise.js
       npm:babel-runtime@5.8.38/core-js/symbol.js
       npm:babel-runtime@5.8.38/regenerator.js
       npm:babel-runtime@5.8.38/regenerator/index.js
       npm:babel-runtime@5.8.38/regenerator/runtime.js
       npm:core-js@1.2.7/library/fn/object/create.js
       npm:core-js@1.2.7/library/fn/object/set-prototype-of.js
       npm:core-js@1.2.7/library/fn/promise.js
       npm:core-js@1.2.7/library/fn/symbol.js
       npm:core-js@1.2.7/library/fn/symbol/index.js
       npm:core-js@1.2.7/library/modules/$.a-function.js
       npm:core-js@1.2.7/library/modules/$.add-to-unscopables.js
       npm:core-js@1.2.7/library/modules/$.an-object.js
       npm:core-js@1.2.7/library/modules/$.classof.js
       npm:core-js@1.2.7/library/modules/$.cof.js
       npm:core-js@1.2.7/library/modules/$.core.js
       npm:core-js@1.2.7/library/modules/$.ctx.js
       npm:core-js@1.2.7/library/modules/$.defined.js
       npm:core-js@1.2.7/library/modules/$.descriptors.js
       npm:core-js@1.2.7/library/modules/$.dom-create.js
       npm:core-js@1.2.7/library/modules/$.enum-keys.js
       npm:core-js@1.2.7/library/modules/$.export.js
       npm:core-js@1.2.7/library/modules/$.fails.js
       npm:core-js@1.2.7/library/modules/$.for-of.js
       npm:core-js@1.2.7/library/modules/$.get-names.js
       npm:core-js@1.2.7/library/modules/$.global.js
       npm:core-js@1.2.7/library/modules/$.has.js
       npm:core-js@1.2.7/library/modules/$.hide.js
       npm:core-js@1.2.7/library/modules/$.html.js
       npm:core-js@1.2.7/library/modules/$.invoke.js
       npm:core-js@1.2.7/library/modules/$.iobject.js
       npm:core-js@1.2.7/library/modules/$.is-array-iter.js
       npm:core-js@1.2.7/library/modules/$.is-array.js
       npm:core-js@1.2.7/library/modules/$.is-object.js
       npm:core-js@1.2.7/library/modules/$.iter-call.js
       npm:core-js@1.2.7/library/modules/$.iter-create.js
       npm:core-js@1.2.7/library/modules/$.iter-define.js
       npm:core-js@1.2.7/library/modules/$.iter-detect.js
       npm:core-js@1.2.7/library/modules/$.iter-step.js
       npm:core-js@1.2.7/library/modules/$.iterators.js
       npm:core-js@1.2.7/library/modules/$.js
       npm:core-js@1.2.7/library/modules/$.keyof.js
       npm:core-js@1.2.7/library/modules/$.library.js
       npm:core-js@1.2.7/library/modules/$.microtask.js
       npm:core-js@1.2.7/library/modules/$.property-desc.js
       npm:core-js@1.2.7/library/modules/$.redefine-all.js
       npm:core-js@1.2.7/library/modules/$.redefine.js
       npm:core-js@1.2.7/library/modules/$.same-value.js
       npm:core-js@1.2.7/library/modules/$.set-proto.js
       npm:core-js@1.2.7/library/modules/$.set-species.js
       npm:core-js@1.2.7/library/modules/$.set-to-string-tag.js
       npm:core-js@1.2.7/library/modules/$.shared.js
       npm:core-js@1.2.7/library/modules/$.species-constructor.js
       npm:core-js@1.2.7/library/modules/$.strict-new.js
       npm:core-js@1.2.7/library/modules/$.string-at.js
       npm:core-js@1.2.7/library/modules/$.task.js
       npm:core-js@1.2.7/library/modules/$.to-integer.js
       npm:core-js@1.2.7/library/modules/$.to-iobject.js
       npm:core-js@1.2.7/library/modules/$.to-length.js
       npm:core-js@1.2.7/library/modules/$.uid.js
       npm:core-js@1.2.7/library/modules/$.wks.js
       npm:core-js@1.2.7/library/modules/core.get-iterator-method.js
       npm:core-js@1.2.7/library/modules/es6.array.iterator.js
       npm:core-js@1.2.7/library/modules/es6.object.set-prototype-of.js
       npm:core-js@1.2.7/library/modules/es6.object.to-string.js
       npm:core-js@1.2.7/library/modules/es6.promise.js
       npm:core-js@1.2.7/library/modules/es6.string.iterator.js
       npm:core-js@1.2.7/library/modules/es6.symbol.js
       npm:core-js@1.2.7/library/modules/web.dom.iterable.js
       npm:process@0.11.8.js
       npm:process@0.11.8/browser.js
     
ok   build.js added to config bundles.
ok   Built into build.js with source maps, unminified.
```

Everything ok.

**Comment by kawazoe** [comment]
Have you tried running the site? It throws an exception and the bundle will not load. This is a runtime issue; not a compile time one.

**Comment by screendriver** [comment]
I modified your `index.html` because it does not include the `build.js` to

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Plugin-Sass Bundle</title>
    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script src="build.js"></script>
    <script>
        SystemJS.import('source.js');
    </script>
</head>
<body>
    <div>This should be blue</div>
</body>
</html>
```

after that I did a

```js
❯ jspm bundle source.js
     Building the bundle tree for source.js...

       source.js
       source.scss!github:mobilexag/plugin-sass@0.4.6.js

ok   Built into build.js with source maps, unminified.
```

And run a `npm run serve`. It looks like

![screenshot](https://cloud.githubusercontent.com/assets/149248/17847001/f28e48ea-684b-11e6-9724-679bf3359d9a.png)

**Comment by screendriver** [comment]
And I saw a typo in your `package.json`:

```json
{
  ...
  "scripts": {
    "install": "jspm install",
    "bundle": "jspm bundle scss --inject",
    "serve": "lite-server"
  },
  ...
}
```

You have to bundle your main JavaScript entry point file (in your case `source.js`) and not the name of what you want. So replace `"bundle": "jspm bundle scss --inject",` with `"bundle": "jspm bundle source.js",` and everything works fine.

**Comment by kawazoe** [comment]
My goal was not to bundle my application. I want to bundle your plugin because it take upward of 30 seconds to load all its dependencies on some of our computers. This make the Write+Save+Refresh workflow unbearable.

I know that your plugin bundles scss files correctly. That's not the point. The issue is that it is impossible to bundle the plugin itself. This works fine for all the other plugins we use which includes Babel, TypeScript, Plugin-Css, Plugin-Text and Plugin-Json.

As for including the `build.js` file in the ìndex.html` file, this is not necessary. That's actually the whole point of the --inject parameter. Instead of manually changing your html file, it tells SystemJS that it can find some packages in the bundle which short-circuit the import process.

**Comment by screendriver** [comment]
Ok I understand. I didn't know, until now, that you can bundle plugins and what's the reason for it.

Is there an API for that? I don't know how to implement this at the moment.

**Comment by kawazoe** [comment]
Well, the bundling process is the same as for every other code. There is no special API involved. As for the reason, without bundling, loading our application with all the plugins can take upward of 2 minutes because of the 700+ requests that are made initially. With most of the plugins bundled, it goes down to 300 requests, mostly because of the code-js dependency in sass.

Like I said, the main issue is that `__moduleName` is apparently not handled correctly. For some reason, it does not work when bundled. If you do not absolutely need it, you could stop using that feature of SystemJS and it would work like a charm. The other fix is to figure out why it is not bundling correctly.

**Comment by screendriver** [comment]
If I remove `__moduleName` then `jspm bundle` fails because it cannot find the files anymore. Guy Bedford told me in the past that I have to add `{ name: __moduleName }` to `System.import()`. Since then it worked. So I don't know how to avoid this.

You can easily reproduce it: just remove `{ name: __moduleName }` and do a `npm run test:bundle` on this repo.

**Comment by kawazoe** [comment]
I will take a look at this when I have a chance. I will submit a PR if I find a way around this problem.

**Comment by kawazoe** [comment]
Ok... So after a lot of research and playing around, it turns out that what I was trying to do would not work anyway. Basically, `__moduleName` is normally use to deal with dynamic dependencies which SASS itself is full of. There is no way to get rid of it, nor is it something that you might actually want to do in your case. I guess I'll just have to find another way to speed up my development process.

I'm closing this issue now.
