### ISSUE TITLE
rewrite url and asset bundler

### ISSUE THREAD

**Issue by sormy** [mobilexag/plugin-sass#71]
Hello.

It looks like url rewriting doesn't work, so packages like bootstrap 3, open sans font, font awesome can't find their assets.

I have an idea of minimal resolver with automatic asset copy in bundle.

Will you be open for accepting PR?

**Comment by screendriver** [comment]
Thank you for the suggestion. Any pull request is welcome 😎 👍

**Comment by sormy** [comment]
This PR should fix issue: https://github.com/mobilexag/plugin-sass/pull/73
